# Generated by Django 2.1.3 on 2018-12-03 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('finish_date', models.DateTimeField(verbose_name='finish date')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.Aircraft')),
            ],
        ),
    ]
