# Generated by Django 2.1.3 on 2018-12-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resgister', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[(1, 'ATR'), (2, 'A320'), (3, 'A321'), (4, 'B787'), (5, 'B777'), (6, 'A330'), (7, 'A350')], default=1, max_length=1)),
            ],
        ),
    ]
