# Generated by Django 2.1.3 on 2018-12-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='type',
            field=models.IntegerField(choices=[(1, 'ATR'), (2, 'A320'), (3, 'A321'), (4, 'B787'), (5, 'B777'), (6, 'A330'), (7, 'A350')], default=1),
        ),
    ]
