# Generated by Django 2.1.3 on 2018-12-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_auto_20181218_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
