# Generated by Django 2.1.3 on 2018-12-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0006_auto_20181202_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
