# Generated by Django 2.1.3 on 2018-12-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0009_auto_20181202_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
